#!/usr/bin/env python
"""
Spyder Editor

This is a temporary script file.
"""

#
# gps_sim_node
# 
# A GPS simulator node, that reads output from robot simulation
# and converts to standard GPS NMEA strings for testing. 
#
# Val Schmidt
# Center for Coastal and Ocean Mapping
# University of New Hampshire
# Copyright 2017, All rights reserved.

#import MissionManager.MissionManager
#import MissionManager.untitled0
#import MissionManager.MissionReader
import MissionManager.DontRunAgroundBen
import rospy
#from asv_msgs.msg import Depth

if __name__ == '__main__':
    
    c = MissionManager.DontRunAgroundBen.DontRunAgroundBen()
    
    while not rospy.is_shutdown():
        try:
            c.dontRunAgroundBen()	    
           
        except rospy.ROSInterruptException:
            print "Error of unknown origin."
            pass
        
