#!/usr/bin/env python
"""
Spyder Editor

This is a temporary script file.
"""

#
# gps_sim_node
# 
# A GPS simulator node, that reads output from robot simulation
# and converts to standard GPS NMEA strings for testing. 
#
# Val Schmidt
# Center for Coastal and Ocean Mapping
# University of New Hampshire
# Copyright 2017, All rights reserved.

import MissionManager.MissionManager
import MissionManager.untitled0
import MissionManager.untitled1
import MissionManager.untitled2
import MissionManager.MissionReader
import MissionManager.DontRunAgroundBen
import rospy
from asv_msgs.msg import Depth

if __name__ == '__main__':
    
    a = MissionManager.missionmanager_v0.MissMan_Node()
    b = MissionManager.missionmanager_v1.MissMan_Node()
    c = MissionManager.missionmanager_v2.MissMan_Node()
    
    
    while not rospy.is_shutdown():
        try:
            #a.runOnce()
            #b.runOnce()
            c.runOnce()
            
        except rospy.ROSInterruptException:
            print "Error of unknown origin."
            pass
    
